Improve simulator functionality
STFC-ICD-Research-and-Design/supermusr-data-pipeline pull request #249
Opened 2024-09-05 11:22 UTC by Modularius

## Summary of changes

1. Changed `unwrap`s to `expect`s in `build_messages.rs`
2. Changed `send_trace_message` to `send_digitiser_trace_message` and integrated edits in `send_messages.rs`,  `simulation.rs`, `engine.rs` and others.
3. Added `Trace` struct for channel traces in `event_lists.rs` and refactored
4. Added `IntConstant` and `TextConstant` types
5. Added `EnsureDelayMs` action
6. Improved error handling

## Instruction for review/testing

General code review as the simulator was successfully tested in the pipeline.

2024-09-06 09:39 UTC, DanNixon requested changes
I don't like the amount of `unwrap` and `expect`. Now that we have a standard for how error handling should happen I would like new and refactored code to use it (arguably it is of less concern for the simulator but I see a lot of the same elsewhere, anything related to tracing for example).

2024-09-06 09:44 UTC, Modularius commented on simulator/src/integrated/simulation_elements/utils.rs
> +                env::var(environment_variable).unwrap().parse().unwrap()
It is useful for varying the number of digitisers. As changing this requires the aggregator to be restarted, the only safe way to do it is to restart the whole pipeline with the number of digitisers defined by environment variable.

2024-09-06 11:05 UTC, Modularius commented
There were considerably more `unwrap`s than I realised. I've replaced them with `anyhow`s (they inform the user of invalid JSON), and all remaining `except`s should be impossible.

2024-09-06 13:44 UTC, DanNixon commented
> I've replaced them with `anyhow`s (they inform the user of invalid JSON)

See https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/blob/main/docs/style.md#crab-error-handling-rules, `anyhow` outside of the return type of `main()` is prohibited.

2024-09-10 14:03 UTC, DanNixon approved these changes

2024-09-10 14:03 UTC, merged