Fix excessive memory usage in aggregator
STFC-ICD-Research-and-Design/supermusr-data-pipeline pull request #269
Opened 2024-11-06 16:03 UTC by Modularius

## Summary of changes

- Replaces `JoinSet` method of producing `frame_event_list` messages to Kakfa, with a dedicated long-running thread which is tasked with emitting frames to Kafka.
- Every call to `cache_poll` drains the cache of completed frames from the front, until an incomplete frame is reached, and sends them to the dedicated thread.
- Frames are emitted in the order they were begun (i.e. when its first digitiser event message arrived).

## Instruction for review/testing

General code review. This change been tested and verified with simulated data, and on HiFi.

Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/265.

2024-11-07 11:48 UTC, DanNixon requested changes

2024-11-07 11:48 UTC, DanNixon commented on digitiser-aggregator/src/main.rs
> +type ChannelSender = Sender<AggregatedFrame<EventData>>;
Could this type have a more descriptive name? `ChannelSender` is rather abstract.

2024-11-07 11:48 UTC, DanNixon commented on digitiser-aggregator/src/main.rs
> +    let channel_send = create_producer_thread(
```suggestion
    let channel_send = create_producer_task(
```

2024-11-07 11:48 UTC, DanNixon commented on digitiser-aggregator/src/main.rs
> +) -> anyhow::Result<()> {
Could something other than `anyhow::Result` be used here?

2024-11-07 11:48 UTC, DanNixon commented on digitiser-aggregator/src/main.rs
> +) -> anyhow::Result<()> {
Same here.

2024-11-07 11:48 UTC, DanNixon commented on digitiser-aggregator/src/main.rs
> +) -> anyhow::Result<()> {
Same here.

2024-11-07 19:34 UTC, Modularius commented on digitiser-aggregator/src/main.rs
> +type TrySendAggregatedFrameError = TrySendError<AggregatedFrame<EventData>>;
Unfortunately, Rust won't let you implement `Error` for `()`.

2024-11-08 15:48 UTC, DanNixon approved these changes

2024-11-08 15:49 UTC, merged