Resume Run Functionality
STFC-ICD-Research-and-Design/supermusr-data-pipeline pull request #273
Opened 2024-11-21 14:13 UTC by Modularius

## Summary of changes

Added behaviour for the Nexus Writer to resume a run if it was interrupted by the component going down.
- A file with extension ".partial_run" is added to the local path when a run_start is received. This file is removed when the nexus file is transferred to the archive (signalling a successful run).
- When the nexus writer starts, any ".partial_run" files in the local path are read and runs re-created (as .partial_run files indicate that a previous instance of nexus writer had failed).

## Instruction for review/testing

General code review.

Tool was tested with simulated data.

2024-11-26 11:43 UTC, Modularius commented
I considered that, but thought it would couple the design of the file format with this functionality. I'd rather avoid that if possible.

2024-11-26 12:34 UTC, DanNixon commented
> I considered that, but thought it would couple the design of the file format with this functionality. I'd rather avoid that if possible.

But all the information is already recorded in the data file (and can be assumed to always be there, as it is all pretty basic information). I can't see why just using that is not the most straightforward.

2024-11-28 10:14 UTC, Modularius commented
On second thoughts, you are right that this is the cleanest way to do it.

2024-12-09 13:02 UTC, DanNixon requested changes

2024-12-09 13:02 UTC, DanNixon commented on nexus-writer/src/nexus/run_parameters.rs
> +    pub(crate) fn get_hdf5_path_buf(path: &Path, run_name: &str) -> PathBuf {
```suggestion
    pub(crate) fn get_hdf5_filename(path: &Path, run_name: &str) -> PathBuf {
```

2024-12-09 13:02 UTC, DanNixon commented on nexus-writer/src/nexus/run.rs
> +            hdf5.push_message_to_runfile(message)?; //&self.parameters,
Is the comment relevant?

2024-12-09 13:02 UTC, DanNixon commented on nexus-writer/Test1.nxs
What is this file for?

2024-12-09 13:02 UTC, DanNixon commented on nexus-writer/TestRun1.nxs
What is this file for?

2024-12-09 13:11 UTC, Modularius commented on nexus-writer/Test1.nxs
These seem to have been created by the test module at some point. That was not supposed to happen of course, and doesn't happen any more. I think it was an artefact of an alternative use of file handling I was trying (but then abandoned).

2024-12-09 14:08 UTC, merged