Unauthenticated kafka connections
STFC-ICD-Research-and-Design/supermusr-data-pipeline pull request #48
Opened 2023-08-15 10:37 UTC by henrydenny246

Allows the `username` and `password` command line arguments to be omitted, in which case an unauthenticated Kafka connection is able to be created instead.

2023-08-15 12:05 UTC, DanNixon commented
Looks like you need to rebase this, run `git fetch` followed by `git rebase origin/main`.

2023-08-15 13:58 UTC, henrydenny246 commented
I've run the commands but can't see a difference. Has it worked?

2023-08-17 08:25 UTC, DanNixon requested changes
Could the new function also be used in the other binaries that handle Kafka connections?

2023-08-17 08:25 UTC, DanNixon commented on common/src/lib.rs
> +    opt_username: &Option<String>,
```suggestion
    username: &Option<String>,
```

2023-08-17 08:25 UTC, DanNixon commented on common/src/lib.rs
> +pub fn generate_client_config(
```suggestion
pub fn generate_kafka_client_config(
```

2023-08-17 08:25 UTC, DanNixon commented on common/src/lib.rs
> +use rdkafka::config::ClientConfig;
Could this be moved up so that it is between the end of modules and start of types, this is the general format used elsewhere in the codebase.

2023-08-17 14:30 UTC, DanNixon approved these changes
:+1:

2023-08-17 14:31 UTC, merged