Move package and container image builds to Nix
STFC-ICD-Research-and-Design/supermusr-data-pipeline pull request #63
Opened 2023-09-19 10:19 UTC by Henry-Denny

Closes #62

2023-09-19 13:12 UTC, DanNixon commented on flake.nix
> +          streaming-types = import ./streaming-types { inherit pkgs naersk' version git_revision nativeBuildInputs buildInputs; };
`straming-types` is a library used by other crates, so should not appear here.

2023-09-19 13:14 UTC, DanNixon commented on kafka-daq-report/default.nix
> +        "HTTP_SERVER_ADDRESS=0.0.0.0:8000"
```suggestion
```

2023-09-19 15:52 UTC, DanNixon commented on .github/workflows/ci.yml
> +      - name: Start MinIO
This step is not required.

2023-09-20 06:34 UTC, DanNixon commented on kafka-daq-report/default.nix
> +    entrypoint = pkgs.writeShellApplication {
I don't believe there is.

2023-09-20 09:34 UTC, DanNixon commented on events-to-histogram/default.nix
> -  container-image = let
We still want the container images, they just do not need the entrypoint script.

See https://github.com/DanNixon/satori/blob/main/archiver/default.nix#L24 for an example.

2023-10-11 12:06 UTC, DanNixon requested changes
Looks good.

One other thing that is worth doing now, could you restructure the `default.nix` files for each component as per https://github.com/DanNixon/satori/commit/49a5ff5d3b6a6be91755bfe7e7a2c8b615cb5640, this will get around the issue we saw earlier with `nix flake show` giving an error.

2023-10-11 12:06 UTC, DanNixon commented on kafka-daq-report/default.nix
> +    nativeBuildInputs = nativeBuildInputs ++ [ pkgs.makeWrapper ];
```suggestion
    nativeBuildInputs = nativeBuildInputs;
```

2023-10-11 12:06 UTC, DanNixon commented on kafka-daq-report/default.nix
> +    HDF5_DIR = "${hdf5-joined}";
This is not needed unless the binary depends on `hdf5`.

2023-10-11 12:06 UTC, DanNixon commented on simulator/default.nix
> +    nativeBuildInputs = nativeBuildInputs ++ [ pkgs.makeWrapper ];
```suggestion
    nativeBuildInputs = nativeBuildInputs;
```

2023-10-11 12:06 UTC, DanNixon commented on stream-to-file/default.nix
> +    nativeBuildInputs = nativeBuildInputs ++ [ pkgs.makeWrapper ];
```suggestion
    nativeBuildInputs = nativeBuildInputs;
```

2023-10-11 12:06 UTC, DanNixon commented on trace-archiver/default.nix
> +    nativeBuildInputs = nativeBuildInputs ++ [ pkgs.makeWrapper ];
```suggestion
    nativeBuildInputs = nativeBuildInputs;
```

2023-10-11 12:06 UTC, DanNixon commented on trace-to-events/default.nix
> +    nativeBuildInputs = nativeBuildInputs ++ [ pkgs.makeWrapper ];
```suggestion
    nativeBuildInputs = nativeBuildInputs;
```

2023-10-11 12:06 UTC, DanNixon commented on .github/workflows/ci.yml
> +      - name: Build and push container image
Comment out this step for now, we can add the container builds later on.

2023-10-11 13:08 UTC, Henry-Denny commented
> Looks good.
> 
> One other thing that is worth doing now, could you restructure the `default.nix` files for each component as per [DanNixon/satori@49a5ff5](https://github.com/DanNixon/satori/commit/49a5ff5d3b6a6be91755bfe7e7a2c8b615cb5640), this will get around the issue we saw earlier with `nix flake show` giving an error.

Thank you. In terms of restructuring, I can't see a difference between the `default.nix` files in https://github.com/DanNixon/satori/commit/49a5ff5d3b6a6be91755bfe7e7a2c8b615cb5640 and the ones currently in https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/pull/63/commits/f69ff9c4398c30e8eb30939358a4f1e053852bce. The only difference I can spot is the `entryPoint` and `postInstall` code, but I thought that these were left out intentionally.

2023-10-11 13:12 UTC, DanNixon commented
> > Looks good.
> > One other thing that is worth doing now, could you restructure the `default.nix` files for each component as per [DanNixon/satori@49a5ff5](https://github.com/DanNixon/satori/commit/49a5ff5d3b6a6be91755bfe7e7a2c8b615cb5640), this will get around the issue we saw earlier with `nix flake show` giving an error.
> 
> Thank you. In terms of restructuring, I can't see a difference between the `default.nix` files in [DanNixon/satori@49a5ff5](https://github.com/DanNixon/satori/commit/49a5ff5d3b6a6be91755bfe7e7a2c8b615cb5640) and the ones currently in [f69ff9c](https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/commit/f69ff9c4398c30e8eb30939358a4f1e053852bce). The only difference I can spot is the `entryPoint` and `postInstall` code, but I thought that these were left out intentionally.

Looking at the commit I linked to in isolation should show the changes I am referring to, specifically, it makes everything under `packages` a derivation, i.e. what is currently `trace-archiver.package` and `trace-archiver.container-image become `trace-archiver` and `trace-arhciver-container-image`.

2023-10-14 15:10 UTC, DanNixon approved these changes
Looks good, there will be some follow up work to do, but as it stands this is a good amount of progress and all the foundations and essentials are in place.

2023-10-14 15:10 UTC, merged