Trace to events
STFC-ICD-Research-and-Design/supermusr-data-pipeline pull request #80
Opened 2023-11-06 17:47 UTC by Modularius

This adds the trace-to-pulses crate as well as modifies the trace-to-events crate.

2023-11-07 09:20 UTC, DanNixon commented
Is there no way this PR can be split up? 7k lines is way too big for a single PR.

2023-11-07 09:31 UTC, Modularius commented
Yes, I can submit the trace-to-pulses crate separately.

2023-11-07 09:32 UTC, DanNixon commented
A few things that would form a starting point of making this more reviewable:
- Move the code from the `trace-to-pulses` crate into `trace-to-events` (the former is just support code for the latter, so I see no real reason for the extra crate)
- Change the visibility modifiers from `pub` to `pub (crate)` (this will show you where you have code that is not actually used)
- The unused code can then be removed (this is not to say that it is not valuable, just that it does not yet belong on `main`)

2023-11-07 09:32 UTC, DanNixon commented
> Yes, I can submit the trace-to-pulses crate separately.

That will not really help, that crate is the vast majority of the code in this PR.

2023-11-27 09:21 UTC, DanNixon requested changes
An initial look over. There are more places with [style](https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/blob/main/docs/style.md) issues that I did not comment on.

2023-11-27 11:25 UTC, Modularius commented on trace-to-events/src/main.rs
> +    save_file_name: Option<String>,
It is useful to have the option at this point. As flat-buffer event messages are limited in what they can capture at this point. Perhaps this should be made a dev-only feature?

2023-11-28 10:14 UTC, Modularius commented on trace-to-events/src/parameters.rs
> +    pub(crate) save_path: &'a str,
This is to ensure the save folder is created if it doesn't exist. Also it is easier to manipulate the file name if it separate. There is often more than one file created, e.g. filename_raw.csv, filename_smoothed.csv, filename_pulses.csv, for each stage of the process. As the saving feature is likely to be redundant when we've debugged it all, I don't think this is too much a problem. I've changed the Strings to PathBufs however.

2023-11-28 10:31 UTC, DanNixon commented on trace-to-events/src/parameters.rs
> +    pub(crate) save_path: &'a str,
I don't think creating directories should be the job of this tool, this goes against behaviour of a lot of other command line tools that manipulate/output files.

Perhaps it is easier to just specify an output directory.

2023-11-28 11:35 UTC, DanNixon requested changes

2023-11-28 11:35 UTC, DanNixon commented on trace-to-events/src/pulse_detection/detectors/basic_muon_detector.rs
> +                    //if end.time - start.time <= 0 { Problem }
Should something be done here?

2023-11-28 11:35 UTC, DanNixon commented on trace-to-events/src/pulse_detection/detectors/basic_muon_detector.rs
> +                        //.map(|tv| tv)
```suggestion
```

2023-11-30 12:41 UTC, DanNixon approved these changes

2023-11-30 12:41 UTC, merged