TDEngine Trace archiver
STFC-ICD-Research-and-Design/supermusr-data-pipeline pull request #87
Opened 2023-11-20 11:25 UTC by Modularius

2023-11-20 17:02 UTC, DanNixon requested changes
This is from an initial look, I haven't looked at all the files yet but the style comments apply to pretty much everything.

I think the `docker-compose` strategy needs looking at, it does not really fit well with the rest of the project. I think assuming Redpanda is available is fine, include documentation on starting TDengine via Podman, and assume the archiver will be run (for development at least) via `cargo run`.

2023-11-27 14:51 UTC, Modularius commented on Cargo.toml
> -  "kafka-daq-report",
This has been corrected now

2023-11-27 14:55 UTC, Modularius commented
I think I missed a few, it'll be ready the next commit though

2023-11-27 18:32 UTC, DanNixon commented
I still see `kafka-daq-report` removed.

2023-11-29 12:45 UTC, DanNixon approved these changes

2023-11-29 12:45 UTC, merged